// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: coupon.proto

package coupon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CouponAddReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                                   // 优惠券名称（如:上海周中打车券）
	Type             int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                                                  // 类型: 1=折扣券, 2=现金券, 3=免费乘车
	Value            float64                `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`                                               // 面值/折扣率（现金存金额，折扣存0-100的数值）
	MinAmount        float64                `protobuf:"fixed64,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`                      // 最低消费门槛（满X元可用）
	TimeLocationRule *TimeLocationRule      `protobuf:"bytes,5,opt,name=time_location_rule,json=timeLocationRule,proto3" json:"time_location_rule,omitempty"` // 适用时间地点规则
	IssueCount       int32                  `protobuf:"varint,6,opt,name=issue_count,json=issueCount,proto3" json:"issue_count,omitempty"`                    // 发行总数量限制
	Status           int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`                                              // 状态: 1=草稿, 2=已发布, 3=已下架, 4=已结束
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CouponAddReq) Reset() {
	*x = CouponAddReq{}
	mi := &file_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponAddReq) ProtoMessage() {}

func (x *CouponAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponAddReq.ProtoReflect.Descriptor instead.
func (*CouponAddReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponAddReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponAddReq) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CouponAddReq) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponAddReq) GetTimeLocationRule() *TimeLocationRule {
	if x != nil {
		return x.TimeLocationRule
	}
	return nil
}

func (x *CouponAddReq) GetIssueCount() int32 {
	if x != nil {
		return x.IssueCount
	}
	return 0
}

func (x *CouponAddReq) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CouponAddResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponAddResp) Reset() {
	*x = CouponAddResp{}
	mi := &file_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponAddResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponAddResp) ProtoMessage() {}

func (x *CouponAddResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponAddResp.ProtoReflect.Descriptor instead.
func (*CouponAddResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *CouponAddResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         string                 `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"` // "07:00"
	End           string                 `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`     // "09:00"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *TimeRange) GetStart() string {
	if x != nil {
		return x.Start
	}
	return ""
}

func (x *TimeRange) GetEnd() string {
	if x != nil {
		return x.End
	}
	return ""
}

// 对应Go的TimeLocationRule结构体
type TimeLocationRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cities        []string               `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`                           // 适用城市列表
	Areas         []string               `protobuf:"bytes,2,rep,name=areas,proto3" json:"areas,omitempty"`                             // 适用行政区列表（可选）
	TimeRanges    []*TimeRange           `protobuf:"bytes,3,rep,name=time_ranges,json=timeRanges,proto3" json:"time_ranges,omitempty"` // 适用时间段列表
	CarTypes      []string               `protobuf:"bytes,4,rep,name=car_types,json=carTypes,proto3" json:"car_types,omitempty"`       // 适用车型列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeLocationRule) Reset() {
	*x = TimeLocationRule{}
	mi := &file_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeLocationRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeLocationRule) ProtoMessage() {}

func (x *TimeLocationRule) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeLocationRule.ProtoReflect.Descriptor instead.
func (*TimeLocationRule) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *TimeLocationRule) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *TimeLocationRule) GetAreas() []string {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *TimeLocationRule) GetTimeRanges() []*TimeRange {
	if x != nil {
		return x.TimeRanges
	}
	return nil
}

func (x *TimeLocationRule) GetCarTypes() []string {
	if x != nil {
		return x.CarTypes
	}
	return nil
}

type CouponIssueReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeLocationId int64                  `protobuf:"varint,2,opt,name=time_location_id,json=timeLocationId,proto3" json:"time_location_id,omitempty"`
	ObtainTime     string                 `protobuf:"bytes,3,opt,name=obtain_time,json=obtainTime,proto3" json:"obtain_time,omitempty"`
	ExpireTime     string                 `protobuf:"bytes,4,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	SourceType     int64                  `protobuf:"varint,5,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CouponIssueReq) Reset() {
	*x = CouponIssueReq{}
	mi := &file_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponIssueReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponIssueReq) ProtoMessage() {}

func (x *CouponIssueReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponIssueReq.ProtoReflect.Descriptor instead.
func (*CouponIssueReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *CouponIssueReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CouponIssueReq) GetTimeLocationId() int64 {
	if x != nil {
		return x.TimeLocationId
	}
	return 0
}

func (x *CouponIssueReq) GetObtainTime() string {
	if x != nil {
		return x.ObtainTime
	}
	return ""
}

func (x *CouponIssueReq) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *CouponIssueReq) GetSourceType() int64 {
	if x != nil {
		return x.SourceType
	}
	return 0
}

type CouponIssueResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponIssueResp) Reset() {
	*x = CouponIssueResp{}
	mi := &file_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponIssueResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponIssueResp) ProtoMessage() {}

func (x *CouponIssueResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponIssueResp.ProtoReflect.Descriptor instead.
func (*CouponIssueResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *CouponIssueResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CouponDisplayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	SourceType    int64                  `protobuf:"varint,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponDisplayReq) Reset() {
	*x = CouponDisplayReq{}
	mi := &file_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponDisplayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponDisplayReq) ProtoMessage() {}

func (x *CouponDisplayReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponDisplayReq.ProtoReflect.Descriptor instead.
func (*CouponDisplayReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *CouponDisplayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CouponDisplayReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponDisplayReq) GetSourceType() int64 {
	if x != nil {
		return x.SourceType
	}
	return 0
}

type CouponDisplayResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*CouponDisplayData   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouponDisplayResp) Reset() {
	*x = CouponDisplayResp{}
	mi := &file_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponDisplayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponDisplayResp) ProtoMessage() {}

func (x *CouponDisplayResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponDisplayResp.ProtoReflect.Descriptor instead.
func (*CouponDisplayResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *CouponDisplayResp) GetData() []*CouponDisplayData {
	if x != nil {
		return x.Data
	}
	return nil
}

type CouponDisplayData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ObtainTime       string                 `protobuf:"bytes,1,opt,name=obtain_time,json=obtainTime,proto3" json:"obtain_time,omitempty"`
	ExpireTime       string                 `protobuf:"bytes,2,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	SourceType       string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Value            string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	MinAmount        float64                `protobuf:"fixed64,6,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	TimeLocationRule string                 `protobuf:"bytes,8,opt,name=time_location_rule,json=timeLocationRule,proto3" json:"time_location_rule,omitempty"`
	Areas            []string               `protobuf:"bytes,7,rep,name=areas,proto3" json:"areas,omitempty"`
	Cities           []string               `protobuf:"bytes,9,rep,name=cities,proto3" json:"cities,omitempty"`
	CarTypes         []string               `protobuf:"bytes,10,rep,name=car_types,json=carTypes,proto3" json:"car_types,omitempty"`
	TimeRanges       string                 `protobuf:"bytes,11,opt,name=time_ranges,json=timeRanges,proto3" json:"time_ranges,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CouponDisplayData) Reset() {
	*x = CouponDisplayData{}
	mi := &file_coupon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponDisplayData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponDisplayData) ProtoMessage() {}

func (x *CouponDisplayData) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponDisplayData.ProtoReflect.Descriptor instead.
func (*CouponDisplayData) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{8}
}

func (x *CouponDisplayData) GetObtainTime() string {
	if x != nil {
		return x.ObtainTime
	}
	return ""
}

func (x *CouponDisplayData) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *CouponDisplayData) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *CouponDisplayData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponDisplayData) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CouponDisplayData) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponDisplayData) GetTimeLocationRule() string {
	if x != nil {
		return x.TimeLocationRule
	}
	return ""
}

func (x *CouponDisplayData) GetAreas() []string {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *CouponDisplayData) GetCities() []string {
	if x != nil {
		return x.Cities
	}
	return nil
}

func (x *CouponDisplayData) GetCarTypes() []string {
	if x != nil {
		return x.CarTypes
	}
	return nil
}

func (x *CouponDisplayData) GetTimeRanges() string {
	if x != nil {
		return x.TimeRanges
	}
	return ""
}

var File_coupon_proto protoreflect.FileDescriptor

const file_coupon_proto_rawDesc = "" +
	"\n" +
	"\fcoupon.proto\x12\x06coupon\"\xec\x01\n" +
	"\fCouponAddReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x01R\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\x01R\tminAmount\x12F\n" +
	"\x12time_location_rule\x18\x05 \x01(\v2\x18.coupon.TimeLocationRuleR\x10timeLocationRule\x12\x1f\n" +
	"\vissue_count\x18\x06 \x01(\x05R\n" +
	"issueCount\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\")\n" +
	"\rCouponAddResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\tTimeRange\x12\x14\n" +
	"\x05start\x18\x01 \x01(\tR\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\tR\x03end\"\x91\x01\n" +
	"\x10TimeLocationRule\x12\x16\n" +
	"\x06cities\x18\x01 \x03(\tR\x06cities\x12\x14\n" +
	"\x05areas\x18\x02 \x03(\tR\x05areas\x122\n" +
	"\vtime_ranges\x18\x03 \x03(\v2\x11.coupon.TimeRangeR\n" +
	"timeRanges\x12\x1b\n" +
	"\tcar_types\x18\x04 \x03(\tR\bcarTypes\"\xb6\x01\n" +
	"\x0eCouponIssueReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12(\n" +
	"\x10time_location_id\x18\x02 \x01(\x03R\x0etimeLocationId\x12\x1f\n" +
	"\vobtain_time\x18\x03 \x01(\tR\n" +
	"obtainTime\x12\x1f\n" +
	"\vexpire_time\x18\x04 \x01(\tR\n" +
	"expireTime\x12\x1f\n" +
	"\vsource_type\x18\x05 \x01(\x03R\n" +
	"sourceType\"+\n" +
	"\x0fCouponIssueResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x10CouponDisplayReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\x03R\n" +
	"sourceType\"B\n" +
	"\x11CouponDisplayResp\x12-\n" +
	"\x04data\x18\x01 \x03(\v2\x19.coupon.CouponDisplayDataR\x04data\"\xd9\x02\n" +
	"\x11CouponDisplayData\x12\x1f\n" +
	"\vobtain_time\x18\x01 \x01(\tR\n" +
	"obtainTime\x12\x1f\n" +
	"\vexpire_time\x18\x02 \x01(\tR\n" +
	"expireTime\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x06 \x01(\x01R\tminAmount\x12,\n" +
	"\x12time_location_rule\x18\b \x01(\tR\x10timeLocationRule\x12\x14\n" +
	"\x05areas\x18\a \x03(\tR\x05areas\x12\x16\n" +
	"\x06cities\x18\t \x03(\tR\x06cities\x12\x1b\n" +
	"\tcar_types\x18\n" +
	" \x03(\tR\bcarTypes\x12\x1f\n" +
	"\vtime_ranges\x18\v \x01(\tR\n" +
	"timeRanges2\xcf\x01\n" +
	"\rCouponService\x128\n" +
	"\tCouponAdd\x12\x14.coupon.CouponAddReq\x1a\x15.coupon.CouponAddResp\x12>\n" +
	"\vCouponIssue\x12\x16.coupon.CouponIssueReq\x1a\x17.coupon.CouponIssueResp\x12D\n" +
	"\rCouponDisplay\x12\x18.coupon.CouponDisplayReq\x1a\x19.coupon.CouponDisplayRespB\x17Z\x15./proto/coupon/couponb\x06proto3"

var (
	file_coupon_proto_rawDescOnce sync.Once
	file_coupon_proto_rawDescData []byte
)

func file_coupon_proto_rawDescGZIP() []byte {
	file_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)))
	})
	return file_coupon_proto_rawDescData
}

var file_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_coupon_proto_goTypes = []any{
	(*CouponAddReq)(nil),      // 0: coupon.CouponAddReq
	(*CouponAddResp)(nil),     // 1: coupon.CouponAddResp
	(*TimeRange)(nil),         // 2: coupon.TimeRange
	(*TimeLocationRule)(nil),  // 3: coupon.TimeLocationRule
	(*CouponIssueReq)(nil),    // 4: coupon.CouponIssueReq
	(*CouponIssueResp)(nil),   // 5: coupon.CouponIssueResp
	(*CouponDisplayReq)(nil),  // 6: coupon.CouponDisplayReq
	(*CouponDisplayResp)(nil), // 7: coupon.CouponDisplayResp
	(*CouponDisplayData)(nil), // 8: coupon.CouponDisplayData
}
var file_coupon_proto_depIdxs = []int32{
	3, // 0: coupon.CouponAddReq.time_location_rule:type_name -> coupon.TimeLocationRule
	2, // 1: coupon.TimeLocationRule.time_ranges:type_name -> coupon.TimeRange
	8, // 2: coupon.CouponDisplayResp.data:type_name -> coupon.CouponDisplayData
	0, // 3: coupon.CouponService.CouponAdd:input_type -> coupon.CouponAddReq
	4, // 4: coupon.CouponService.CouponIssue:input_type -> coupon.CouponIssueReq
	6, // 5: coupon.CouponService.CouponDisplay:input_type -> coupon.CouponDisplayReq
	1, // 6: coupon.CouponService.CouponAdd:output_type -> coupon.CouponAddResp
	5, // 7: coupon.CouponService.CouponIssue:output_type -> coupon.CouponIssueResp
	7, // 8: coupon.CouponService.CouponDisplay:output_type -> coupon.CouponDisplayResp
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_coupon_proto_init() }
func file_coupon_proto_init() {
	if File_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_proto_msgTypes,
	}.Build()
	File_coupon_proto = out.File
	file_coupon_proto_goTypes = nil
	file_coupon_proto_depIdxs = nil
}
